/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'ILockable', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ILockable__factory>
getContractFactory(name: 'LockableNFT', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.LockableNFT__factory>
getContractFactory(name: 'PublicLockableNFT', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PublicLockableNFT__factory>

  getContractAt(name: 'ILockable', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ILockable>
getContractAt(name: 'LockableNFT', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.LockableNFT>
getContractAt(name: 'PublicLockableNFT', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PublicLockableNFT>

  deployContract(name: 'ILockable', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ILockable>
deployContract(name: 'LockableNFT', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LockableNFT>
deployContract(name: 'PublicLockableNFT', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PublicLockableNFT>

  deployContract(name: 'ILockable', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ILockable>
deployContract(name: 'LockableNFT', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LockableNFT>
deployContract(name: 'PublicLockableNFT', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PublicLockableNFT>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  