/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface ILockableInterface extends Interface {
    getFunction(nameOrSignature: "getAuthorities" | "getAuthorityBaseURI" | "isAuthority" | "isLocked" | "lock" | "ownerOf" | "tokenURI" | "transferFrom" | "unlock" | "unlockChallenge"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AddAuthority" | "Lock" | "Mint" | "RemoveAuthority" | "Unlock" | "UpdateProof"): EventFragment;

    encodeFunctionData(functionFragment: 'getAuthorities', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAuthorityBaseURI', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isAuthority', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isLocked', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'lock', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'ownerOf', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'tokenURI', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'unlock', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'unlockChallenge', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'getAuthorities', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAuthorityBaseURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isAuthority', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isLocked', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lock', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ownerOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unlock', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unlockChallenge', data: BytesLike): Result;
  }

  
    export namespace AddAuthorityEvent {
      export type InputTuple = [account: AddressLike, _authorityBaseURI: string];
      export type OutputTuple = [account: string, _authorityBaseURI: string];
      export interface OutputObject {account: string, _authorityBaseURI: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LockEvent {
      export type InputTuple = [tokenId: BigNumberish, challenge: BytesLike];
      export type OutputTuple = [tokenId: bigint, challenge: string];
      export interface OutputObject {tokenId: bigint, challenge: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MintEvent {
      export type InputTuple = [id: BigNumberish, _to: AddressLike, _locked: boolean, _tokenURI: string];
      export type OutputTuple = [id: bigint, _to: string, _locked: boolean, _tokenURI: string];
      export interface OutputObject {id: bigint, _to: string, _locked: boolean, _tokenURI: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RemoveAuthorityEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnlockEvent {
      export type InputTuple = [tokenId: BigNumberish];
      export type OutputTuple = [tokenId: bigint];
      export interface OutputObject {tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UpdateProofEvent {
      export type InputTuple = [tokenId: BigNumberish, challenge: BytesLike];
      export type OutputTuple = [tokenId: bigint, challenge: string];
      export interface OutputObject {tokenId: bigint, challenge: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ILockable extends BaseContract {
    
    connect(runner?: ContractRunner | null): ILockable;
    waitForDeployment(): Promise<this>;

    interface: ILockableInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getAuthorities: TypedContractMethod<
      [],
      [[string[], string[]]],
      'view'
    >
    

    
    getAuthorityBaseURI: TypedContractMethod<
      [account: AddressLike, ],
      [string],
      'view'
    >
    

    
    isAuthority: TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isLocked: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    lock: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    ownerOf: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    tokenURI: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    transferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    unlock: TypedContractMethod<
      [tokenId: BigNumberish, proof: BytesLike, ],
      [void],
      'payable'
    >
    

    
    unlockChallenge: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getAuthorities'): TypedContractMethod<
      [],
      [[string[], string[]]],
      'view'
    >;
getFunction(nameOrSignature: 'getAuthorityBaseURI'): TypedContractMethod<
      [account: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isAuthority'): TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isLocked'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'lock'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'ownerOf'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'tokenURI'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unlock'): TypedContractMethod<
      [tokenId: BigNumberish, proof: BytesLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'unlockChallenge'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;

    getEvent(key: 'AddAuthority'): TypedContractEvent<AddAuthorityEvent.InputTuple, AddAuthorityEvent.OutputTuple, AddAuthorityEvent.OutputObject>;
getEvent(key: 'Lock'): TypedContractEvent<LockEvent.InputTuple, LockEvent.OutputTuple, LockEvent.OutputObject>;
getEvent(key: 'Mint'): TypedContractEvent<MintEvent.InputTuple, MintEvent.OutputTuple, MintEvent.OutputObject>;
getEvent(key: 'RemoveAuthority'): TypedContractEvent<RemoveAuthorityEvent.InputTuple, RemoveAuthorityEvent.OutputTuple, RemoveAuthorityEvent.OutputObject>;
getEvent(key: 'Unlock'): TypedContractEvent<UnlockEvent.InputTuple, UnlockEvent.OutputTuple, UnlockEvent.OutputObject>;
getEvent(key: 'UpdateProof'): TypedContractEvent<UpdateProofEvent.InputTuple, UpdateProofEvent.OutputTuple, UpdateProofEvent.OutputObject>;

    filters: {
      
      'AddAuthority(address,string)': TypedContractEvent<AddAuthorityEvent.InputTuple, AddAuthorityEvent.OutputTuple, AddAuthorityEvent.OutputObject>;
      AddAuthority: TypedContractEvent<AddAuthorityEvent.InputTuple, AddAuthorityEvent.OutputTuple, AddAuthorityEvent.OutputObject>;
    

      'Lock(uint256,bytes32)': TypedContractEvent<LockEvent.InputTuple, LockEvent.OutputTuple, LockEvent.OutputObject>;
      Lock: TypedContractEvent<LockEvent.InputTuple, LockEvent.OutputTuple, LockEvent.OutputObject>;
    

      'Mint(uint256,address,bool,string)': TypedContractEvent<MintEvent.InputTuple, MintEvent.OutputTuple, MintEvent.OutputObject>;
      Mint: TypedContractEvent<MintEvent.InputTuple, MintEvent.OutputTuple, MintEvent.OutputObject>;
    

      'RemoveAuthority(address)': TypedContractEvent<RemoveAuthorityEvent.InputTuple, RemoveAuthorityEvent.OutputTuple, RemoveAuthorityEvent.OutputObject>;
      RemoveAuthority: TypedContractEvent<RemoveAuthorityEvent.InputTuple, RemoveAuthorityEvent.OutputTuple, RemoveAuthorityEvent.OutputObject>;
    

      'Unlock(uint256)': TypedContractEvent<UnlockEvent.InputTuple, UnlockEvent.OutputTuple, UnlockEvent.OutputObject>;
      Unlock: TypedContractEvent<UnlockEvent.InputTuple, UnlockEvent.OutputTuple, UnlockEvent.OutputObject>;
    

      'UpdateProof(uint256,bytes32)': TypedContractEvent<UpdateProofEvent.InputTuple, UpdateProofEvent.OutputTuple, UpdateProofEvent.OutputObject>;
      UpdateProof: TypedContractEvent<UpdateProofEvent.InputTuple, UpdateProofEvent.OutputTuple, UpdateProofEvent.OutputObject>;
    
    };
  }